### ISSUE TITLE
OSError: b'\\Device\\NPF_Loopback: Error opening adapter: The system cannot find the path specified.

### ISSUE THREAD

**Issue by BioMycoBit** [brentvollebregt/whos-on-my-network#10]
Attempted to use both the pre-built module and binary and received the above error

Node: v16.4.2.
Python: 3.9.6

```
WARNING: No route found (no default route?)
[2021-08-26 21:03:42,831] ERROR in app: Exception on /api/run/single-scan [GET]
Traceback (most recent call last):
  File "flask\app.py", line 2070, in wsgi_app
  File "flask\app.py", line 1515, in full_dispatch_request
  File "flask\app.py", line 1513, in full_dispatch_request
  File "flask\app.py", line 1499, in dispatch_request
  File "whos_on_my_network\api.py", line 194, in run_single_scan
  File "whos_on_my_network\service\scanning.py", line 82, in scan_network_single
  File "whos_on_my_network\service\scanning.py", line 25, in __scan_network
  File "scapy\layers\l2.py", line 740, in arping
  File "scapy\sendrecv.py", line 676, in srp
  File "scapy\arch\libpcap.py", line 407, in __init__
  File "scapy\arch\windows\__init__.py", line 704, in open_pcap
  File "scapy\arch\libpcap.py", line 254, in __init__
OSError: b'\\Device\\NPF_Loopback: Error opening adapter: The system cannot find the path specified.  (3)'
192.168.0.22 - - [26/Aug/2021 21:03:42] "GET /api/run/single-scan HTTP/1.1" 500 -
```

**Comment by brentvollebregt** [comment]
Thanks for getting back to this. I've made a change (4362266edebbc9f02af614469d8e560b18377c2f) that will let the user know if the UI if this is an issue.
